"""
Data Models (Dataclasses)
=========================
Pure data structures - koi business logic yahan nahi hogi.
Har jagah typed aur structured data pass hoga, raw dicts nahi.
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass(frozen=True)
class Candle:
    """Single OHLCV candle - immutable (frozen) taake koi accidentally data na badlay."""
    symbol: str
    timeframe: str
    open_time: int          # Unix timestamp ms
    open: float
    high: float
    low: float
    close: float
    volume: float
    close_time: int         # Unix timestamp ms
    quote_volume: float
    trades_count: int
    taker_buy_base_volume: float
    taker_buy_quote_volume: float


@dataclass
class IndicatorSnapshot:
    """Ek candle ke liye tamam computed indicators ka snapshot."""
    symbol: str
    timeframe: str
    open_time: int
    close: float
    ema_fast: Optional[float] = None    # EMA 20
    ema_slow: Optional[float] = None    # EMA 50
    rsi: Optional[float] = None         # RSI 14
    atr: Optional[float] = None         # ATR 14


@dataclass(frozen=True)
class SwingPoint:
    """Chart par detected Swing High ya Swing Low."""
    symbol: str
    timeframe: str
    open_time: int
    price: float
    swing_type: str         # "SWING_HIGH" or "SWING_LOW"
    bar_index: int          # Position in candle array


@dataclass(frozen=True)
class StructureLabel:
    """Market structure ka label: HH, HL, LH, LL."""
    open_time: int
    price: float
    label: str              # "HH", "HL", "LH", "LL"
    swing_type: str         # "SWING_HIGH" or "SWING_LOW"


@dataclass
class MarketRegime:
    """Kisi symbol+timeframe ka current market regime (trend ya range)."""
    symbol: str
    timeframe: str
    trend: str                              # "UPTREND", "DOWNTREND", "RANGING"
    structure_labels: List[StructureLabel] = field(default_factory=list)
    last_swing_high_price: Optional[float] = None
    last_swing_low_price: Optional[float] = None
    confidence: str = "LOW"                 # "LOW", "MEDIUM", "HIGH"


# ── Strategy & Trading Models ─────────────────────────────────


@dataclass
class Signal:
    """Trade signal generated by strategy engine."""
    signal_id: str                  # Unique ID (timestamp-based)
    symbol: str
    direction: str                  # "LONG" or "SHORT"
    entry_price: float
    stop_loss: float
    take_profit_1: float            # 1:2 R:R target
    take_profit_2: float            # 1:3 R:R target
    position_size: float            # Calculated from risk manager
    risk_amount: float              # Dollar amount at risk
    risk_reward_ratio: float
    confidence: str                 # "LOW", "MEDIUM", "HIGH"
    reason: str                     # Human readable entry reason
    status: str = "ACTIVE"          # "ACTIVE", "FILLED", "EXPIRED", "CANCELLED"
    created_at: str = ""            # ISO timestamp
    timeframe: str = "1h"
    trend_tf: str = "4h"            # Higher timeframe trend used


@dataclass
class Position:
    """An open paper trading position."""
    position_id: str
    signal_id: str                  # Which signal created this position
    symbol: str
    direction: str                  # "LONG" or "SHORT"
    entry_price: float
    current_price: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: float
    quantity: float
    unrealized_pnl: float = 0.0
    status: str = "OPEN"            # "OPEN", "CLOSED"
    opened_at: str = ""


@dataclass
class Trade:
    """A completed (closed) paper trade."""
    trade_id: str
    signal_id: str
    symbol: str
    direction: str
    entry_price: float
    exit_price: float
    quantity: float
    pnl: float                      # Realized P&L in USDT
    r_multiple: float               # How many R achieved (1R = risked amount)
    exit_reason: str                # "STOP_LOSS", "TAKE_PROFIT_1", "TAKE_PROFIT_2", "MANUAL"
    entry_reason: str
    opened_at: str = ""
    closed_at: str = ""


@dataclass
class AccountState:
    """Paper trading account snapshot."""
    balance: float
    equity: float                   # Balance + unrealized P&L
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    avg_r_multiple: float = 0.0
    open_positions: int = 0

